# Generated by Django 5.1.2 on 2024-11-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Description',
            field=models.CharField(default='No description available', max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='Image',
            field=models.CharField(blank=True, default='default_image.jpg', max_length=255),
        ),
    ]
