# Generated by Django 5.1.2 on 2024-11-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Description',
            field=models.CharField(blank=True, default='No description available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Image',
            field=models.CharField(blank=True, default='default_image.jpg', max_length=255, null=True),
        ),
    ]
